version: '3.8'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
      - "3001:3001"
      - "3000:3000"
    volumes:
      - ./Volumes/Jenkins/var/jenkins_home:/var/jenkins_home
      - ./Volumes/Jenkins/var/run/docker.sock:/var/run/docker.sock
  bitbucket:
    container_name: bitbucket
    image: atlassian/bitbucket
    ports:
      - "7990:7990"
    expose:
      - "7990:7990"
    volumes:
      - ./Volumes/BitBucket:/var/atlassian/application-data/bitbucket

